layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: tobi8ur
  # instagram: your_username
  # keybase: your_username
  linkedin: tobi8ur
  medium: tobiburrahman786
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: tobi8ur
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/android/android.png

  - name: Kotlin
    web_url: https://github.com/topics/kotlin
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/kotlin/kotlin.png

  - name: Spring Boot
    web_url: https://github.com/topics/spring-boot
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/spring-boot/spring-boot.png
